AllCops:
  Include:
  - app/**/*.rb
  - Rakefile
  - '**/Gemfile'
  - config.ru
  Exclude:
  - config/**/*
  - db/**/*
  - spec/**/*
  - bin/**/*
  - lib/tasks/*
  TargetRubyVersion: 2.6
  StyleGuideCopsOnly: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 12
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/SymbolArray:
  # Turned off because the associated auto-correct makes a real mess
  Enabled: false